<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>1d41768f-44c7-4a30-82ca-2805903f8580</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="taskflow-client\src\components\task\**" />
    <Content Remove="taskflow-client\src\components\task\**" />
    <EmbeddedResource Remove="taskflow-client\src\components\task\**" />
    <None Remove="taskflow-client\src\components\task\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.2.0" />
    <PackageReference Include="FluentValidation.AspNetCore" Version="11.3.1" />
    <PackageReference Include="HtmlSanitizer" Version="9.2.995" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.10">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Mappings\" />
    <Folder Include="taskflow-client\src\components\NewFolder1\" />
    <Folder Include="taskflow-client\src\components\NewFolder\" />
    <Folder Include="taskflow-client\src\components\Tasks\TaskDetailsModal\" />
    <Folder Include="taskflow-client\src\features\tasks\components\" />
  </ItemGroup>

</Project>
